[project]
name = "langchain-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.9",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.35",
    "python-dotenv>=1.1.1",
]
